PREFIX ldcOnt: <https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/SeedlingOntology#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX aida:  <https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/InterchangeOntology#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>

SELECT ?subject ?type1 ?type2 ?conf_value1 ?conf_value2
WHERE {
	?statement a               rdf:Statement .
	?statement rdf:object      ?type1 .
	?statement rdf:object      ?type2 .
	?statement rdf:predicate   rdf:type .
	?statement rdf:subject     ?subject .
	?statement aida:confidence ?confidence1 .
	?statement aida:confidence ?confidence2 .

	?confidence1 a aida:Confidence .
	?confidence1 aida:confidenceValue ?conf_value1 .

	?confidence2 a aida:Confidence .
	?confidence2 aida:confidenceValue ?conf_value2 .

	FILTER(?type1 != ?type2 && ?conf_value1 != ?conf_value2) .
}
