PREFIX ldcOnt: <https://raw.githubusercontent.com/NextCenturyCorporation/AIDA-Interchange-Format/master/java/src/main/resources/com/ncc/aif/ontologies/LDCOntologyM36#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX aida:  <https://raw.githubusercontent.com/NextCenturyCorporation/AIDA-Interchange-Format/master/java/src/main/resources/com/ncc/aif/ontologies/InterchangeOntology#>
PREFIX cfn:   <https://verdi.nextcentury.com/custom-function/>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>

# Mentions of all entities in text documents

PREFIX ldc: <https://raw.githubusercontent.com/NextCenturyCorporation/AIDA-Interchange-Format/master/java/src/main/resources/com/ncc/aif/ontologies/LdcAnnotations#>
SELECT DISTINCT
  ?member
  (GROUP_CONCAT(?attribute ; SEPARATOR = ", ") AS ?attributes)

WHERE {
    ?statement2           a                             aida:ClusterMembership .
    ?statement2           aida:cluster                  ?cluster .
    ?statement2           aida:clusterMember            ?_member .
    ?_member               aida:attributes               ?_attribute .
    bind(strafter(str(?_attribute),str(aida:)) as ?attribute)
    bind(strafter(str(?_member),str(ldc:)) as ?member)
}

GROUP BY ?member
